package com.example.nomorescrolling;

import android.app.*;
import android.content.*;
import android.os.*;
import android.app.usage.*;
import androidx.core.app.NotificationCompat;
import android.util.Log;
import java.util.*;

public class UsageMonitorService extends Service {
    private Handler handler; private Runnable runnable; private UsageStatsManager usageStatsManager; private SharedPreferences prefs;
    @Override public void onCreate(){ super.onCreate(); prefs=getSharedPreferences("nm_prefs",MODE_PRIVATE); usageStatsManager=(UsageStatsManager)getSystemService(Context.USAGE_STATS_SERVICE); startForegroundNotification(); handler=new Handler(Looper.getMainLooper()); runnable=this::tick; handler.post(runnable); }
    private void startForegroundNotification(){ String channelId=createNotificationChannel(); Notification n=new NotificationCompat.Builder(this,channelId).setContentTitle("NoMoreScrolling").setContentText("Monitoring").setSmallIcon(android.R.drawable.sym_def_app_icon).setPriority(NotificationCompat.PRIORITY_LOW).build(); startForeground(1337,n); }
    private String createNotificationChannel(){ String id="nm_monitor_channel"; NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE); if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O){ NotificationChannel ch=new NotificationChannel(id,"Monitoring",NotificationManager.IMPORTANCE_LOW); nm.createNotificationChannel(ch);} return id; }
    private void tick(){ try{ String foreground=getForegroundAppPackage(); if(foreground!=null) accumulateSecondsForPackage(foreground,5); }catch(Exception e){ Log.e("UsageService","tick",e);} finally{ handler.postDelayed(runnable,5000); } }
    private String getForegroundAppPackage(){ long end=System.currentTimeMillis(); long begin=end-1000L*10; UsageEvents events=usageStatsManager.queryEvents(begin,end); UsageEvents.Event ev=new UsageEvents.Event(); String fg=null; while(events.hasNextEvent()){ events.getNextEvent(ev); if(ev.getEventType()==UsageEvents.Event.MOVE_TO_FOREGROUND) fg=ev.getPackageName(); } return fg; }
    private void accumulateSecondsForPackage(String pkg,int secondsToAdd){ int limit=prefs.getInt("limit_"+pkg,-1); if(limit<=0) return; String day=todayKey(); String secKey="sec_"+pkg+"_"+day; int secs=prefs.getInt(secKey,0); secs+=secondsToAdd; prefs.edit().putInt(secKey,secs).apply(); int mins=secs/60; if(!prefs.getBoolean("warned80_"+pkg+"_"+day,false) && mins>=Math.floor(limit*0.8)){ send80Warning(pkg,mins,limit); prefs.edit().putBoolean("warned80_"+pkg+"_"+day,true).apply(); } if(!prefs.getBoolean("reached_"+pkg+"_"+day,false) && mins>=limit){ prefs.edit().putBoolean("reached_"+pkg+"_"+day,true).apply(); boolean blockMode=prefs.getBoolean("block_"+pkg,true); onLimitReached(pkg,blockMode);} }
    private void send80Warning(String pkg,int mins,int limit){ NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE); String id="nm_warning_channel"; if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O){ NotificationChannel ch=new NotificationChannel(id,"Warnings",NotificationManager.IMPORTANCE_HIGH); nm.createNotificationChannel(ch);} String appName=pkg; try{ appName=getPackageManager().getApplicationLabel(getPackageManager().getApplicationInfo(pkg,0)).toString(); }catch(Exception ignored){} Notification n=new NotificationCompat.Builder(this,id).setContentTitle("Almost there").setContentText("You're at 80% of your daily limit for "+appName).setSmallIcon(android.R.drawable.sym_def_app_icon).setPriority(NotificationCompat.PRIORITY_HIGH).build(); nm.notify((pkg+"_warn").hashCode(),n); }
    private void onLimitReached(String pkg, boolean blockMode){ if(blockMode){ Intent i=new Intent(this,BlockActivity.class); i.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK|Intent.FLAG_ACTIVITY_CLEAR_TASK); i.putExtra("pkg",pkg); startActivity(i); } else { NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE); String id="nm_reached_channel"; if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O){ NotificationChannel ch=new NotificationChannel(id,"Limits",NotificationManager.IMPORTANCE_HIGH); nm.createNotificationChannel(ch);} String appName=pkg; try{ appName=getPackageManager().getApplicationLabel(getPackageManager().getApplicationInfo(pkg,0)).toString(); }catch(Exception ignored){} Notification n=new NotificationCompat.Builder(this,id).setContentTitle("Time limit reached").setContentText("You reached your limit for "+appName).setSmallIcon(android.R.drawable.sym_def_app_icon).setPriority(NotificationCompat.PRIORITY_HIGH).setAutoCancel(true).build(); nm.notify((pkg+"_reached").hashCode(),n); } }
    private String todayKey(){ Calendar c=Calendar.getInstance(); return String.format(Locale.US, "%04d-%02d-%02d", c.get(Calendar.YEAR), c.get(Calendar.MONTH)+1, c.get(Calendar.DAY_OF_MONTH)); }
    @Override public void onDestroy(){ handler.removeCallbacks(runnable); super.onDestroy(); }
    @Override public IBinder onBind(Intent intent){ return null; }
}
